### PR TITLE
Add section about verifying keys in Enigmail (issue 39)

### PR DESCRIPTION
**Pull request by tommycollison**
This PR is in reference to https://github.com/freedomofpress/encryption-works/issues/39 -- adding suggested text to the PGP section about how to verify someone's key in Enigmail.

### CODE REVIEW

**Comment by harlo** [comment]
Your first commit introduced a blank file called `branch`, which doesn't need to be included. (see https://github.com/freedomofpress/encryption-works/pull/45/files)

Remove it from your local repo with `git rm branch -f`and commit again into your issue_39 branch.

Other than that, you're doing :+1:

**Comment by conorsch** [comment]
@harlo Good eye on the nit. @tommycollison Can you explain this section?

>By having a key signed by colleagues and other people you trust, it's harder to be the victim of an attack where someone tries to steal your identity.

To be clear, having your key signed just increases the ostensible trustworthiness of the key, thereby making a genuine key compromise *worse*, rather than better, since folks are more likely to believe that the key comes from "you". Overall, the phrase "an attack where someone tries to steal your identity" is vague, and perhaps could be clarified with a more specific situation.

Ultimately, if you don't protect your private key, then anyone can "steal your identity" by signing or decrypting as you.

**Comment by tommycollison** [comment]
@Harlo Thanks! Removed and committed. 

@conorsch Hm, yeah, that section's addressing a different issue and is unclear. I've had people create public keys in my e-mail address as a nuisance, and I was pointing out that signing the true key will mitigate the problem (since key servers rarely remove keys and there isn't much to be done about it). It's not an identity theft issue so much as a way of streamlining the process of secure communication. 

I assume we're advocating for signed keys, though, so how does this sound as a rewrite? 

> ### How To Verify Someone's Key in Enigmail and View Signatures

If you're a journalist trying to get to grips with these privacy tools, it's useful to get together with colleagues and help one another out with setup. In addition, you can increase the trustworthiness of a colleague's key by signing it. In essence, you're publicly asserting that you trust that a person's key belongs to that person, and wasn't created by someone else.

Here's how to verify that a key belongs to the person it should: 

- Meet your colleagues face-to-face. Each person should bring their own laptop.

[...]

**Comment by conorsch** [comment]
@tommycollison The rewrite is crystal clear. If @harlo doesn't have any further edits, add a commit that implements the rewrite, and we should be all set.

**Comment by tommycollison** [comment]
@harlo You good with the proposed rewrite?

**Pull request closed without merging**
