### PR TITLE
Standardize em-dash

### PR DESCRIPTION
**Pull request by fowlslegs**
Originally, I was just going to change one double-hyphen to a proper em dash,
but I went ahead and standardized our usage of em dashes. @trevor suggested no
spaces before and after them. I don't think it matters as long as it's
consistent—which now it is.

Signed-off-by: Noah Vesely <fowlslegs@riseup.net>

### CODE REVIEW

**Comment by trevor** [comment]
@fowlslegs wait, what?

**Comment by garrettr** [comment]
@fowlslegs, @trevor is not @trevortimm, and in any case I think you're confusing them with @conorsch, who asked you to standardize on em dashes in https://github.com/freedomofpress/encryption-works/pull/204#issuecomment-157158033.

(Sorry, @trevor!)

**Comment by trevor** [comment]
No prob! :smiley:

**Comment by fowlslegs** [comment]
I was actually thinking of @trevortimm and not @conorsch's https://github.com/freedomofpress/encryption-works/pull/204#issuecomment-157158033 because this is relating to spacing around em dashes, not em dashes themselves, but anyway sorry trevor.

**Pull request merged**
