### PR TITLE
Update the Fighting Chance Section

### PR DESCRIPTION
**Pull request by tommycollison**
As per #67.

I really liked the Snowden op-ed linked, so I've opened with a section of it. I also expanded the section, adding a paragraph from the intro section of EW 1.0 about how dodging NSA surveillance is hard but not impossible.

### CODE REVIEW

**Comment by garrettr** [comment]
This PR has a bunch of stuff about OTR that needs to be removed before it can be merged.

**Comment by garrettr** [comment]
I'd like to edit this a bit more, but I think (once this branch is cleaned up so it only has changes relevant to the "Fighting Chance" section) we can merge it now and re-evaluate it once the rest of the document is more shaped up.

**Comment by tommycollison** [comment]
Fixed!

**Comment by garrettr** [comment]
Rebased and merged into master in e0a374ab2ec625904fcd48878a296f573d848644.

**Pull request closed without merging**
